package com.turnin.common.ml.keywordCategory

enum class KeywordCategory(
    val displayName: String,
    val id: Int,
    val anchorKeywords: List<String>,
) {
    DAILY(displayName = "일상", id = 1, anchorKeywords = DAILY_KEYWORDS),
    FOOD(displayName = "푸드&카페", id = 2, anchorKeywords = FOOD_KEYWORDS),
    FASHION_BEAUTY(displayName = "패션&뷰티", id = 3, anchorKeywords = FASHION_BEAUTY_KEYWORDS),
    TRAVEL(displayName = "여행&아웃도어", id = 4, anchorKeywords = TRAVEL_KEYWORDS),
    FITNESS(displayName = "운동&건강", id = 5, anchorKeywords = FITNESS_KEYWORDS),
    CULTURE(displayName = "문화&예술", id = 6, anchorKeywords = CULTURE_KEYWORDS),
    MUSIC(displayName = "음악&페스티벌", id = 7, anchorKeywords = MUSIC_KEYWORDS),
    PET(displayName = "반려동물", id = 8, anchorKeywords = PET_KEYWORDS),
    INTERIOR(displayName = "리빙&인테리어", id = 9, anchorKeywords = INTERIOR_KEYWORDS),
    EMOTION(displayName = "감정&힐링", id = 10, anchorKeywords = EMOTION_KEYWORDS),
    ROMANCE(displayName = "연애&인간관계", id = 11, anchorKeywords = ROMANCE_KEYWORDS),
    CAREER(displayName = "커리어&공부", id = 12, anchorKeywords = CAREER_KEYWORDS),
    FINANCE(displayName = "경제&재테크", id = 13, anchorKeywords = FINANCE_KEYWORDS),
    TECH(displayName = "IT&테크", id = 14, anchorKeywords = TECH_KEYWORDS),
    GAMING(displayName = "게임", id = 15, anchorKeywords = GAMING_KEYWORDS),
    HUMOR(displayName = "유머&밈", id = 16, anchorKeywords = HUMOR_KEYWORDS),
    HOBBY(displayName = "취미&DIY", id = 17, anchorKeywords = HOBBY_KEYWORDS),
    VEHICLE(displayName = "자동차&바이크", id = 18, anchorKeywords = VEHICLE_KEYWORDS),
    SHOPPING(displayName = "쇼핑&내돈내산", id = 19, anchorKeywords = SHOPPING_KEYWORDS),
    ISSUE(displayName = "시사&이슈", id = 20, anchorKeywords = ISSUE_KEYWORDS),
    ;

    companion object {
        fun fromId(id: Int): KeywordCategory? = entries.find { it.id == id }
    }
}

private val DAILY_KEYWORDS = listOf(
    "일상",
    "데일리",
    "하루",
    "아침",
    "밤",
    "주말",
    "출근",
    "퇴근",
    "집콕",
    "산책",
    "날씨",
    "브이로그",
    "일상기록",
    "루틴",
    "오늘 하루 일상을 기록한다",
    "소소한 일상을 공유한다",
    "daily",
    "vlog",
    "routine",
)

private val FOOD_KEYWORDS = listOf(
    "맛집",
    "먹방",
    "요리",
    "레시피",
    "디저트",
    "카페",
    "커피",
    "브런치",
    "야식",
    "혼밥",
    "배달음식",
    "집밥",
    "술",
    "맛있는 음식을 먹고 기록한다",
    "카페에서 커피를 마신다",
    "food",
    "cafe",
    "coffee",
    "recipe",
)

private val FASHION_BEAUTY_KEYWORDS = listOf(
    "패션",
    "스타일",
    "코디",
    "옷",
    "쇼핑",
    "트렌드",
    "빈티지",
    "악세사리",
    "메이크업",
    "화장품",
    "네일",
    "헤어",
    "향수",
    "스킨케어",
    "오늘의 옷차림을 공유한다",
    "패션과 뷰티 스타일을 기록한다",
    "OOTD",
    "fashion",
    "beauty",
    "makeup",
    "skincare",
)

private val TRAVEL_KEYWORDS = listOf(
    "여행",
    "국내여행",
    "해외여행",
    "캠핑",
    "피크닉",
    "바다",
    "산",
    "호캉스",
    "휴가",
    "백패킹",
    "혼행",
    "여행지에서 일상을 기록한다",
    "자연 속에서 힐링한다",
    "travel",
    "camping",
    "vacation",
    "outdoor",
)

private val FITNESS_KEYWORDS = listOf(
    "헬스",
    "러닝",
    "요가",
    "필라테스",
    "등산",
    "다이어트",
    "건강",
    "홈트",
    "수영",
    "근력운동",
    "오늘 운동을 완료했다",
    "건강한 몸을 만들기 위해 운동한다",
    "fitness",
    "workout",
    "running",
    "yoga",
    "sports",
)

private val CULTURE_KEYWORDS = listOf(
    "영화",
    "드라마",
    "뮤지컬",
    "연극",
    "전시회",
    "미술",
    "박물관",
    "독서",
    "책",
    "웹툰",
    "그림",
    "일러스트",
    "사진",
    "전시회나 공연을 관람한다",
    "책을 읽고 감상을 나눈다",
    "art",
    "photography",
    "illustration",
)

private val MUSIC_KEYWORDS = listOf(
    "음악",
    "플레이리스트",
    "노래",
    "콘서트",
    "페스티벌",
    "밴드",
    "아이돌",
    "덕질",
    "악기",
    "좋아하는 음악을 추천한다",
    "콘서트와 페스티벌을 즐긴다",
    "music",
    "kpop",
    "playlist",
    "concert",
)

private val PET_KEYWORDS = listOf(
    "강아지",
    "고양이",
    "반려동물",
    "반려견",
    "반려묘",
    "귀여운 반려동물과 함께하는 일상",
    "강아지와 산책한다",
    "pet",
    "dog",
    "cat",
)

private val INTERIOR_KEYWORDS = listOf(
    "인테리어",
    "방꾸미기",
    "가구",
    "소품",
    "식물",
    "홈데코",
    "미니멀",
    "청소",
    "자취",
    "방을 예쁘게 꾸민다",
    "홈인테리어와 리빙을 기록한다",
    "interior",
    "homedecor",
    "minimal",
)

private val EMOTION_KEYWORDS = listOf(
    "감성",
    "힐링",
    "위로",
    "우울",
    "행복",
    "불안",
    "외로움",
    "설렘",
    "번아웃",
    "자존감",
    "고민",
    "일기",
    "명상",
    "감정을 글로 기록한다",
    "마음을 치유하고 위로받는다",
    "healing",
    "emotion",
    "anxiety",
    "burnout",
)

private val ROMANCE_KEYWORDS = listOf(
    "연애",
    "데이트",
    "커플",
    "친구",
    "우정",
    "가족",
    "결혼",
    "이별",
    "짝사랑",
    "인간관계",
    "연애와 사랑에 대해 이야기한다",
    "소중한 사람들과의 관계를 기록한다",
    "relationship",
    "love",
    "dating",
    "friendship",
)

private val CAREER_KEYWORDS = listOf(
    "커리어",
    "이직",
    "취업",
    "공부",
    "스터디",
    "자격증",
    "성장",
    "동기부여",
    "회사생활",
    "업무",
    "일과 커리어에 대해 고민한다",
    "공부하고 자기계발을 한다",
    "career",
    "work",
    "study",
    "growth",
)

private val FINANCE_KEYWORDS = listOf(
    "재테크",
    "주식",
    "투자",
    "부동산",
    "가상화폐",
    "절약",
    "가계부",
    "소비",
    "경제",
    "돈을 모으고 재테크를 한다",
    "소비와 투자를 기록한다",
    "finance",
    "investment",
    "stock",
)

private val TECH_KEYWORDS = listOf(
    "IT",
    "개발",
    "코딩",
    "인공지능",
    "소프트웨어",
    "앱",
    "테크",
    "전자기기",
    "개발과 기술에 대해 이야기한다",
    "새로운 기술과 전자기기를 탐구한다",
    "tech",
    "coding",
    "software",
    "developer",
)

private val GAMING_KEYWORDS = listOf(
    "게임",
    "콘솔",
    "모바일게임",
    "온라인게임",
    "게임을 플레이하고 기록한다",
    "game",
    "gaming",
)

private val HUMOR_KEYWORDS = listOf(
    "유머",
    "밈",
    "예능",
    "개그",
    "웃음",
    "웃긴 짤과 밈을 공유한다",
    "funny",
    "meme",
    "humor",
)

private val HOBBY_KEYWORDS = listOf(
    "취미",
    "베이킹",
    "드로잉",
    "카메라",
    "수집",
    "공예",
    "뜨개질",
    "DIY",
    "취미 활동을 즐기고 기록한다",
    "hobby",
    "craft",
    "baking",
    "diy",
)

private val VEHICLE_KEYWORDS = listOf(
    "자동차",
    "바이크",
    "드라이브",
    "라이딩",
    "튜닝",
    "자동차와 바이크를 즐긴다",
    "car",
    "bike",
    "drive",
)

private val SHOPPING_KEYWORDS = listOf(
    "쇼핑",
    "언박싱",
    "할인",
    "직구",
    "구매후기",
    "구매한 제품을 솔직하게 리뷰한다",
    "shopping",
    "unboxing",
    "review",
)

private val ISSUE_KEYWORDS = listOf(
    "시사",
    "뉴스",
    "이슈",
    "트렌드",
    "토론",
    "사회 이슈와 트렌드를 이야기한다",
    "trend",
    "news",
    "issue",
)
